SELECT Q'[Mother's Day]' FROM DUAL;
SELECT Q'!Mother's Day!' FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMTAT ='DD-MON-RR';

SELECT EMPLOYEE_ID,TO_CHAR(HIRE_DATE,'YYYY-MM-DD')
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY') BETWEEN 2000 AND 2005

DESC EMPLOYEES

CREATE TABLE TEST
(ID NUMBER(5),HIREDATE DATE);
ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY';
INSERT INTO TEST (ID,HIREDATE)
VALUES(10,'12-JUN-2098');
SELECT * FROM TEST;

UNDEFINE B
DEFINE B='DEPARTMENT_ID'
DEFINE B
SET VERIFY ON
SET VERIFY OFF
SELECT &A,&B
FROM EMPLOYEES
WHERE &B= &C;

-- LOWER
SELECT LAST_NAME, upper(LAST_NAME) 
FROM EMPLOYEES
WHERE upper(LAST_NAME) = 'WHALEN';

--INITCAP
SELECT INITCAP('TEST ORG') FROM DUAL;

--CONCAT
SELECT LAST_NAME,FIRST_NAME,
CONCAT(LAST_NAME,FIRST_NAME,SALARY) FROM EMPLOYEES
WHERE EMPLOYEE_ID=100;

--SUBSTR
SELECT LAST_NAME, SUBSTR(LAST_NAME,-2,1) 
FROM EMPLOYEES
WHERE EMPLOYEE_ID=100;

--LENGTH
SELECT LAST_NAME, LENGTH(LAST_NAME) 
FROM EMPLOYEES
WHERE EMPLOYEE_ID=100;

--INSTR
SELECT INSTR('Hello World','W') FROM DUAL;

--LPAD
SELECT LAST_NAME,LPAD(LAST_NAME,12,' ') FROM EMPLOYEES
WHERE DEPARTMENT_ID=30;

--RPAD
SELECT LAST_NAME,RPAD(LAST_NAME,12,' ') FROM EMPLOYEES
WHERE DEPARTMENT_ID=30;

SELECT SALARY,RPAD(SALARY,10,'-') FROM EMPLOYEES
WHERE DEPARTMENT_ID=30;

-- NESTED FUNCTION
SELECT LAST_NAME,UPPER(CONCAT(SUBSTR(LAST_NAME,1,8),'_US')) "RESULT"
FROM EMPLOYEES
WHERE DEPARTMENT_ID=60;

-- ROUND 
SELECT LPAD(ROUND(45.926,-1),10) "    RESULT" FROM DUAL;

-- TRUNC
SELECT LPAD(TRUNC(45.926,-1),10) "    RESULT" FROM DUAL;

--CEIL
SELECT CEIL(2.83) FROM DUAL;
--FLOOR
SELECT FLOOR(2.83) FROM DUAL;
--MOD 
SELECT MOD(1600,300) FROM DUAL;

SELECT EMPLOYEE_ID,LAST_NAME
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID,2) = 0;

-- DATE DATA
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-RR';

SELECT LAST_NAME,TO_CHAR(HIRE_DATE,'YYYY-MON-DD') HIREDATE
FROM EMPLOYEES
WHERE HIRE_DATE < '01-FEB-03';

SELECT TO_CHAR(SYSDATE,'YYYY MM DD HH24:MI:SS AM') FROM DUAL;

SELECT ROUND(SYSDATE,'MONTH') FROM DUAL;
SELECT HIRE_DATE,ROUND(HIRE_DATE,'MONTH') FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

SELECT ROUND(SYSDATE,'YEAR') FROM DUAL;
SELECT HIRE_DATE,ROUND(HIRE_DATE,'YEAR') FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;

SELECT TRUNC(SYSDATE,'MONTH') FROM DUAL;
SELECT HIRE_DATE,TRUNC(HIRE_DATE,'MONTH') FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;

SELECT ROUND(SYSDATE,'YEAR') FROM DUAL;
SELECT HIRE_DATE,TRUNC(HIRE_DATE,'YEAR') FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;

-- TO_CHAR
NUMBER --> CHARACTER
SELECT SALARY,TO_CHAR(SALARY,'$999,999.00') FROM EMPLOYEES
WHERE DEPARTMENT_ID=30;

SELECT SALARY,TO_CHAR(SALARY,'L000,000.00') FROM EMPLOYEES
WHERE DEPARTMENT_ID=30;

DATE --> CHARACTER
SELECT HIRE_DATE,TO_CHAR(HIRE_DATE,'YYYY MONTH DAY J DDSPTH') HIREDATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID=30;

-- TO_DATE (CHAR->DATE)
SELECT SYSDATE FROM DUAL;
SELECT EMPLOYEE_ID,HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE > '10-JAN-05';

SELECT EMPLOYEE_ID,HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE > TO_DATE('05-10-JAN','RR-DD-MON');

--TO_NUMBER (CHAR->NUMBER)
SELECT EMPLOYEE_ID,SALARY
FROM EMPLOYEES
WHERE SALARY > TO_NUMBER('$6,000.00','$9,999.99')
AND DEPARTMENT_ID=30;

SELECT EMPLOYEE_ID,SALARY
FROM EMPLOYEES
WHERE SALARY > '$6,000.00'
AND DEPARTMENT_ID=30;

-- GENERAL FUNCTION
- NVL
SELECT EMPLOYEE_ID,NVL(TO_CHAR(COMMISSION_PCT),'NOT FOUND') RESULT
FROM EMPLOYEES
WHERE DEPARTMENT_ID=60;

SELECT EMPLOYEE_ID,SALARY,
COMMISSION_PCT,SALARY*NVL(COMMISSION_PCT,1) RESULT
FROM EMPLOYEES
WHERE DEPARTMENT_ID=60;

SELECT EMPLOYEE_ID,SALARY,
COMMISSION_PCT,NVL2(COMMISSION_PCT,'SALARY+COMM','SALARY') INCOME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (50,80);

SELECT FIRST_NAME, LENGTH(FIRST_NAME) "EXPR1",
       LAST_NAME, LENGTH(LAST_NAME) "EXPR2",
       NULLIF(LENGTH(FIRST_NAME),LENGTH(LAST_NAME)) RESULT
FROM EMPLOYEES;       