SELECT E.EMPLOYEE_ID,E.JOB_ID,J.JOB_TITLE,D.DEPARTMENT_NAME,L.CITY
FROM EMPLOYEES E,JOBS J,DEPARTMENTS D,LOCATIONS L
WHERE E.JOB_ID = J.JOB_ID AND E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND D.LOCATION_ID=L.LOCATION_ID

SELECT E.EMPLOYEE_ID,J.JOB_TITLE,JOB_ID
FROM JOBS J NATURAL JOIN EMPLOYEES E  

SELECT  E.EMPLOYEE_ID,J.JOB_TITLE,J.JOB_ID
FROM JOBS J JOIN EMPLOYEES E USING (JOB_ID) 


SELECT * 
FROM EMPLOYEES E,JOBS J 
WHERE E.JOB_ID=E.JOB_ID

SELECT e.employee_id,e.last_name,l.city, d.department_name
FROM locations l JOIN departments d
ON (l.location_id=d.location_id)
JOIN employees e 
ON (d.department_id=e.department_id)
AND l.location_id = 1400;


SELECT M.EMPLOYEE_ID,M.LAST_NAME,E.EMPLOYEE_ID,E.LAST_NAME,E.MANAGER_ID
FROM EMPLOYEES M JOIN EMPLOYEES E
ON (M.EMPLOYEE_ID=E.MANAGER_ID)
AND M.EMPLOYEE_ID=101

SELECT employee_id, last_name, job_id, salary
FROM employees
WHERE salary = ANY (SELECT salary FROM employees WHERE job_id = 'IT_PROG')
AND job_id <> 'IT_PROG';


SELECT first_name, department_id, salary
FROM employees
WHERE salary IN (SELECT min(salary) FROM employees GROUP BY department_id)
AND department_id IN (SELECT DISTINCT DEPARTMENT_ID FROM employees)


SELECT * FROM EMPLOYEES;

SELECT E.EMPLOYEE_ID, E.JOB_ID, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D, LOCATIONS L
WHERE E.JOB_ID = J.JOB_ID AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID;


SELECT *
FROM EMPLOYEES E NATURAL JOIN JOBS J

SELECT *
FROM JOBS JOIN EMPLOYEES USING(JOB_ID)
JOIN DEPARTMENTS USING(DEPARTMENT_ID)

SELECT E.EMPLOYEE_ID, E.LAST_NAME, L.CITY, D.DEPARTMENT_NAME
FROM LOCATIONS L JOIN DEPARTMENTS D
ON (L.LOCATION_ID = D.LOCATION_ID)
JOIN EMPLOYEES E
ON (D.DEPARTMENT_ID = E.DEPARTMENT_ID)
WHERE L.LOCATION_ID = 1400;

SELECT M.EMPLOYEE_ID, M.LAST_NAME, E.EMPLOYEE_ID, E.LAST_NAME
FROM EMPLOYEES M JOIN EMPLOYEES E
ON (M.EMPLOYEE_ID = E.MANAGER_ID)
AND M.EMPLOYEE_ID = 101

SELECT e.last_name, d.department_id, d.department_name
FROM employees e FULL OUTER JOIN departments d
ON (e.department_id = d.department_id) ;

SELECT employee_id, last_name, job_id, salary
FROM employees
WHERE salary IN
 (SELECT salary
 FROM employees
WHERE job_id = 'IT_PROG')
AND job_id <> 'IT_PROG';

SELECT FIRST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE SALARY IN
(SELECT MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID)
AND DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES);

SELECT emp.last_name
FROM employees emp
WHERE emp.employee_id IN
 (SELECT mgr.manager_id
 FROM employees mgr);
 
DESC JOB_HISTORY

SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID FROM JOB_HISTORY
WHERE EMPLOYEE_ID = 176
MINUS
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176;

SELECT location_id, department_name "Department",
 TO_CHAR(NULL) "Warehouse location"
FROM departments
UNION
SELECT location_id, TO_CHAR(NULL) "Department",
 state_province
FROM locations;

CREATE TABLE DEPT
(DEPTID NUMBER(10) CONSTRAINT DEPT_DEPTID_PK PRIMARY KEY,
DEPTNAME VARCHAR2(20) CONSTRAINT DEPT_DEPTNAME_NN NOT NULL,
CITY CHAR(10));

INSERT INTO DEPT VALUES (10, 'SALES', 'SEOUL');
COMMIT;

INSERT INTO DEPT VALUES (30, 'HR', 'BUSAN');
INSERT INTO DEPT VALUES (40, 'HR', 'BUSAN');
ROLLBACK;
INSERT INTO DEPT VALUES (50, 'HR', 'BUSAN');
INSERT INTO DEPT VALUES (60, 'HR', 'BUSAN');
COMMIT;
INSERT INTO DEPT VALUES (70, 'HR', 'BUSAN');
ROLLBACK;

SELECT * FROM DEPT;

CREATE TABLE EMP
(EMPID NUMBER(10) PRIMARY KEY, 
EMPNAME VARCHAR2(20) NOT NULL,
STARTDATE DATE,
SALARY NUMBER(10,2),
MARRIAGE CHAR(1),
DEPTID NUMBER(10),
CONSTRAINT MARRIAGE_CK CHECK (MARRIAGE IN ('Y','N')),
CONSTRAINT EMP_DEPTID_FK FOREIGN KEY(DEPTID) REFERENCES DEPT (DEPTID));